{% set name = "sphinxcontrib-httpdomain" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c2dfe6ca282d75f66df333869bb0ce7331c01b475db6809ff9d107b7cdfe04b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - sphinx >=1.6
    - six

test:
  imports:
    - sphinxcontrib

about:
  home: https://github.com/sphinx-contrib/httpdomain
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx domain for describing HTTP APIs
  description: |
    This contrib extension, `sphinxcontrib.httpdomain¡, provides a Sphinx domain
     for describing HTTP APIs.
  doc_url: https://sphinxcontrib-httpdomain.readthedocs.io/en/stable/
  dev_url: https://github.com/sphinx-contrib/httpdomain

extra:
  recipe-maintainers:
    - carlodri
